### ISSUE TITLE
Prevent enter CloudFalre's DDoS/captacha protected sites

### ISSUE THREAD

**Issue by angwdev** [tpopela/fedora-user-agent-chrome#13] opened 2022-05-02 00:56 UTC
This extension causes a loop in CloudFlare DDoS protection system, making it impossible to access the sites.

**Comment by angwdev** [comment] 2022-05-02 00:57
Chrome 101.0.4951.41
Fedora 35

**Comment by tpopela** [comment] 2022-05-02 09:06
Duplicate of https://github.com/tpopela/fedora-user-agent-chrome/issues/11 (as the cause is the same)

**Closed as completed by tpopela** 2022-05-02 09:06 UTC
