### ISSUE TITLE
Why has this been installed?

### ISSUE THREAD

**Issue by resynth1943** [tpopela/fedora-user-agent-chrome#10] opened 2020-10-27 23:28 UTC
This extension was installed without my consent. Seeing as this extension greatly improves fingerprinting surface, might I suggest you query users prior to installation?

**Comment by tpopela** [comment] 2020-10-29 07:21
Thank you @resynth1943 for raising the issue. Marking this as a duplicate of https://github.com/tpopela/fedora-user-agent-chrome/issues/2

**Closed as completed by tpopela** 2020-10-29 07:21 UTC

**Comment by resynth1943** [comment] 2020-10-29 13:11
Well, instead of closing everything, why not solve the problem?
